server:
  port: 8081
  servlet:
    context-path: /crud
    
spring:
  application:
    name: crud
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
#     dialect: org.hibernate.dialect.MySQL5InnoDBDialect  
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/udemyProdutoCrud
    username: postgres
    password: 1234

security:
  jwt:
    token:
      secret-key: chave_microservices

rabbitmq:
    host: localhost 
    port: 5672
    username: guest
    password: guest
    
crud:
  rabbitmq:
    exchange: crud.exchange
    routingkey: crud.produto.routingkey


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka
        